default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_database_development
test:
  <<: *default
  database: my_database_test

production:
  <<: *default
  # TODO: figure out how to add to Gemfile but not require postgres locally.
  adapter: postgresql
  database: my_database_production
  username: postgres
  password: # password
